<a href="https://colab.research.google.com/github/Hussainaquib/Python-Programs/blob/main/MathsPrograms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Write a Python program to display the current date and time.**

In [ ]:
#method -1
# Getting current date and time using now().
# importing datetime module for now()
import datetime
# using now() to get current time
current_time = datetime.datetime.now()
# Printing value of now.
print("Time now at greenwich meridian is:", current_time)

#method-2
import time
curr_time = time.strftime("%H:%M:%S", time.localtime())
print("Current Time is :", curr_time)

Time now at greenwich meridian is: 2022-11-02 16:50:09.158393
Current Time is : 16:50:09


**Write a Python program which accepts the radius of a circle from the user and compute the area.**

In [ ]:
r= int(input("enter a radius of circle:"))
area=3.14*r*r
print("Area of circle is:",area)

enter a radius of circle:2
Area of circle is: 12.56


**Write a Python program which accepts a sequence of comma-separated numbers from user and generate a list and a tuple with those numbers**

In [ ]:
values = input("Input some comma seprated numbers : ")
a = values.split(",")
print('List : ',a)



Input some comma seprated numbers : 3,4,5,6
List :  ['3', '4', '5', '6']


**Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.**

In [ ]:
n=int(input("enter a number"))
a=n*10+n
b=n*100+a
print(n+a+b)

enter a number5
615


**Write a Python program to display the examination schedule. (extract the date from exam_st_date).**

In [ ]:
exam_st_date = (11,12,2014)
print( "The examination will start from : %i / %i / %i"%exam_st_date)

The examination will start from : 11 / 12 / 2014


**Write a Python program to print the calendar of a given month and year.
Note : Use 'calendar' module.**

In [ ]:
import calendar
y = int(input("Input the year : "))
m = int(input("Input the month : "))
print(calendar.month(y, m))

Input the year : 2022
Input the month : 11
   November 2022
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30



**Write a Python program to calculate number of days between two dates.
Sample dates : (2014, 7, 2), (2014, 7, 11)
Expected output : 9 days**

In [ ]:
from datetime import date
f_date = date(2014, 7, 2)
l_date = date(2014, 7, 11)
delta = l_date - f_date
print(delta.days)

9


**Write a Python program to get the volume of a sphere with radius 6**

In [ ]:
r = int(input("enter a radius of circle:"))
v = 4/3*3.14*r*r*r
print("volume of sphere is",v)

enter a radius of circle:6
volume of sphere is 904.3199999999998


**Write a Python program to get the difference between a given number and 17, if the number is greater than 17 return double the absolute difference**

In [ ]:
n=int(input("enter a number:"))
def difference(n):
    if n <= 17:
        return 17 - n
    else:
        return (n - 17) * 2 

print(difference(n))

enter a number:22
10


**Write a Python program to calculate the sum of three given numbers, if the values are equal then return three times of their sum**

In [ ]:
a=int(input("enter a first number:"))
b=int(input("enter a second number:"))
c=int(input("enter a third number:"))
if (a==b and b==c and c==a):
  print(3*a)
else:
  print(a+b+c)

enter a first number:2
enter a second number:3
enter a third number:4
9


**Write a Python program to find whether a given number (accept from the user) is even or odd, print out an appropriate message to the user**

In [ ]:
n = int(input("enter a number:"))
if n%2==0:
  print("number is even")
else:
  print("number is odd")

enter a number:23
number is odd


**Write a Python program to count the number 4 in a given list.**

In [ ]:
lst = []
n = int(input("Enter number of elements : "))
  
for i in range(0, n):
    ele = int(input())
  
    lst.append(ele)
b = lst.count(4)
print("the frequency of given number is",b)

Enter number of elements : 5
4
3
3
4
4
the frequency of given number is 3


**number guessing game**

In [ ]:
winning_number = 43
guess = 1
number = int(input("guess a number between 1 and 100:"))
game_over = False
while not game_over:
  if number == winning_number:
    print(f"you win and you guessed this number in {guess} times")
    game_over = True
  else:
    if number < winning_number:
      print("too low ")
      guess +=1
      number  = int(input("guess again:"))
    else:
      print("too high")
      guess += 1
      number  = int(input("guess again:"))

guess a number between 1 and 100:34
too low 
guess again:43
you win and you guessed this number in 2 times


In [ ]:
import random
winning_number = random.randint(1,101)
guess = 1
number = int(input("guess a number between 1 and 100:"))
print(f"your {guess} guess is done")
game_over = False
for guess in range(1,5):
  if number == winning_number:
    print(f"you win and you guessed this number in {guess} times")
  else:
    if number < winning_number:
      print("too low ")
      guess +=1
      number = int(input(f"guess a number between 1 and 100:"))
      print(f"your {guess} guess is done")
    else:
      print("too high")
      guess += 1
      number = int(input("guess a number between 1 and 100:"))
      print(f"your {guess} guess is done")
else:
  print("YOU LOSS and your guess time is over")

guess a number between 1 and 100:50
your 1 guess is done
too high
guess a number between 1 and 100:25
your 2 guess is done
too high
guess a number between 1 and 100:12
your 3 guess is done
too low 
guess a number between 1 and 100:18
your 4 guess is done
too high
guess a number between 1 and 100:15
your 5 guess is done
YOU LOSS and your guess time is over


**GCD of two number by using function**

In [ ]:
a = int(input())
b = int(input())
def gcd(a,b):
    result=min(a,b)
    while result:
        if a%result==0 and b%result==0:
            break
        result-=1
    return result
print(f"gcd of {a} and {b} is {gcd(a,b)}")

56
98
gcd of 56 and 98 is 14


**GCD of two number without function**

In [ ]:
a = int(input())
b = int(input())
result=min(a,b)
while result:
    if a%result==0 and b%result==0:
        break
    result-=1
print(f"gcd of {a} and {b} is {result}")

56
98
gcd of 56 and 98 is 14


**LCM of two number**

In [ ]:
a = int(input())
b = int(input())
result=min(a,b)
while result:
    if a%result==0 and b%result==0:
        break
    result-=1
print(f"LCM of {a} and {b} is {(a*b)//result}")

15
20
LCM of 15 and 20 is 60


**A number is divisible by 2 or not**

In [ ]:
num = int(input())
res = [int(x) for x in str(num)]
if res[-1]%2==0:
  print(f"{num} is divisible by 2")
else:
  print(f"{num} is not divisible by 2")

3895
3895 is not divisible by 2


**A number is divisible by 3 or not**

In [ ]:
num = int(input())
res = [int(x) for x in str(num)]
p = sum(res)
if p%3==0:
  print(f"{num} is divisible by 3")
else:
  print(f"{num} is not divisible by 3")

34875
34875 is divisible by 3


**A number is divisible by 4 or not**

In [ ]:
num = int(input("enter number greater than 10 :"))
res = [int(x) for x in str(num)]
if ((res[-1]+10*res[-2])%4==0):
  print(f"{num} is divisible by 4")
else:
  print(f"{num} is not divisible by 4")

enter number greater than 10 :34644
34644 is divisible by 4


**A number is divisible by 5 or not**

In [ ]:
num = int(input())
res = [int(x) for x in str(num)]
if res[-1]==0 or res[-1]==5:
  print(f"{num} is divisible by 5")
else:
  print(f"{num} is not divisible by 5")

56320
56320 is divisible by 5


**A number is divisible by 7 or not**

In [ ]:
from operator import length_hint
num = int(input("enter three or six digit number only:"))
res = [int(x) for x in str(num)]
if length_hint(res)==3:
  if (num)%7==0:
    print(f"{num} is divisible by 7")
  else:
    print(f"{num} is not divisible by 7")
elif length_hint(res)==6:
  if (res[2]*100+res[1]*10+res[0] - res[5]*100+res[4]*10+res[3])%7==0:
    print(f"{num} is divisible by 7")
  else:
    print(f"{num} is not divisible by 7")

enter three or six digit number only:120456
120456 is divisible by 7


**A number is divisible by 11 or not**

In [ ]:
num = int(input())
res = [int(x) for x in str(num)]
a = sum(res[::2])
b = sum(res[1::2])
if abs(a-b)%11==0:
  print(f"{num} is divisible by 11")
else:
  print(f"{num} is not divisible by 11")

12865
12865 is not divisible by 11


**Diophantine Equation:- find ax+by+c=0 has solution or not**

In [ ]:
import math
for i in range(int(input("Enter the number of test cases:"))):
  a,b,c=map(int,input().split())
  if a==0 or b==0:
    print("Wrong input")
  else:
    if c%(math.gcd(a,b))==0:
      print(f"{a}x+{b}y+{c}=0 has a solution")
    else:
      print(f"{a}x+{b}y+{c}=0 has a no solution")

Enter the number of test cases:2
3 2 7
3x+2y+7=0 has a solution
2 4 3
2x+4y+3=0 has a no solution


**Program for numbers are co-prime numbers or not**

In [ ]:
import math
for i in range(int(input("Enter the number of test cases:"))):
  a,b = map(int,input().split())
  if math.gcd(a,b)==1:
    print(f"{a} and {b} are co-prime")
  else:
    print(f"{a} and {b} are not co-prime")

Enter the number of test cases:2
5 15
5 and 15 are not co-prime
4 5
4 and 5 are co-prime


**Count the all co-prime numbers of number
enter by user in the range**

In [ ]:
import math
x = int(input("Enter a number:"))
n = int(input("Enter a range:"))
c = 0
for i in range(1,n):
  if math.gcd(x,i)==1:
    c+=1
print(c)

Enter a number:4
Enter a range:10
5


**Euler's Function :-count all co-prime numbers of n from 1 to n**

In [ ]:
import math
n = int(input("Enter a number:"))
c = 0
for i in range(1,n+1):
  if math.gcd(n,i)==1:
    c+=1
print(c)

Enter a number:10
4


**Total number of onto mapping from A to B**

In [ ]:
from math import comb
m,n = map(int,input("Enter the cardinality of A and B respectively:").split())
sum=0
if m<n:
  print("Onto mapping not exist")
else:
  for r in range(1,n+1):
    a = pow(-1,(n-r))*pow(r,m)*comb(n,r)
    sum+=a
  print(f"Total number of onto mapping from A to B is {sum}")

Enter the cardinality of A and B respectively:6 3
Total number of onto mapping from A to B is 540


**Total number of one-one function from A to B**

In [ ]:
from math import comb
f1=1
f2=1
m,n = map(int,input("Enter the cardinality of A and B respectively:").split())
if m>n:
  print("one-one function not exist")
else:
  for i in range(1,n+1):
    f1 *= i
  for j in range(1,(n-m)+1):
    f2 *= j
  print(f"Total number of one one function from A to B is {f1//f2}")  

Enter the cardinality of A and B respectively:4 5
Total number of one one function from A to B is 120


**Program of Hypothesis testing (z-test) on one sample**

In [ ]:
#this program is only for right and left tailed Hypothesis Testing
import math
import pandas as pd
w = [(2.326,2.054,1.650,1.282),
     (-2.326,-2.054,-1.650,-1.282)]
df = pd.DataFrame(w,columns=[0.01,0.02,0.05,0.10],
                  index=['R','L'])
a1 = int(input("Enter the level of significance : "))
a2 = a/100
n = int(input("Enter the size of sample : "))
x,u = map(float,input("Enter the x and u : ").split())
# sample_mean(x) and population_mean(u)
e = input("Enter population_standard_deviation : ")
psd = float(e)
print()
m = input("Is actually population mean more than given population mean : ")
if m=="yes":
  p=u+1
  print("It is right tailed hypothesis testing")
elif m=="no":
  p=u-1
  print("It is left tailed hypothesis testing")
print()
if n>=30:
  print(f"{n}>=30 hence here we peform z-test")
  z = ((x-u)*math.sqrt(n))/psd
  print(f"z = {z}")
else:
  print("This sample size is not apply on z-test")

if a2==0.01 and p>u:
  z_alpha=df.iloc[0,0]
elif a2==0.02 and p>u:
  z_alpha=df.iloc[0,1]
elif a2==0.05 and p>u:
  z_alpha=df.iloc[0,2]
elif a2==0.10 and p>u:
  z_alpha=df.iloc[0,3]
elif a2==0.01 and p<u:
  z_alpha=df.iloc[0,0]
elif a2==0.02 and p<u:
  z_alpha=df.iloc[0,1]
elif a2==0.05 and p<u:
  z_alpha=df.iloc[0,2]
elif a2==0.10 and p<u:
  z_alpha=df.iloc[0,3]

  
print(f"z_alpha={z_alpha}")
if z_alpha < z:
   print("z_alpha < z hence we are rejecting null hypothesis")
else:
  print("z_alpha > z hence we are accept null hypothesis")

Enter the level of significance : 5
Enter the size of sample : 100
Enter the x and u : 71.8 70
Enter population_standard_deviation : 7.8

Is actually population mean more than given population mean : yes
It is right tailed hypothesis testing

100>=30 hence here we peform z-test
z = 2.307692307692304
z_alpha=1.65
z_alpha < z hence we are rejecting null hypothesis


In [ ]:
x = 71.8
u = 70
n = 100
psd = 7.8
z = ((x-u)*math.sqrt(n))/psd
print(f"z = {z}")

z = 2.307692307692304


**Fibonacci sequence**

In [ ]:
n = int(input())
a = 0
b= 0
c = 1
for i in range(0,n):
  a = b+c
  c = b
  b = a
  print(a,end=" ")

9
1 1 2 3 5 8 13 21 34 

**matrix multiplication**

In [ ]:
A = [[2,2,2],[2,2,2],[2,2,2]]
B = [[2,2,2],[2,2,2],[2,2,2]]
result = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(A)):
  for j in range(len(B)):
    for k in range(len(B)):
      result[i][j]+=A[i][k]*B[k][j]
for r in result:
  print(r)

[12, 12, 12]
[12, 12, 12]
[12, 12, 12]


**GCD of two number**

In [ ]:
import math
a,b = map(int,input().split())
print(math.gcd(a,b))

48 60
12


In [ ]:
def computeGCD(x,y):
  if x>y:
    small=y
  else:
    small=x
  for i in range(1,small+1):
    if ((x%i==0) and (y%i==0)):
      gcd=i
  return gcd
x,y = map(int,input().split())
print("The gcd of x and y is",computeGCD(x,y))

60 48
The gcd of x and y is 12


**Calculating inverse of matrix of any order**

In [ ]:
import numpy as np
import sys

R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
if R!=C:
  sys.exit("wrong input value of row and column")
  
print("Enter the entries in a single line (separated by space): ")

entries = list(map(int, input().split()))

matrix = np.array(entries).reshape(R, C)
det = np.linalg.det(matrix)
if det==0:
  sys.exit("inverse is not defined")
print(np.linalg.inv(matrix))

Enter the number of rows:3
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
3 4 6 1 8 7 3 9 4
[[ 0.26956522 -0.33043478  0.17391304]
 [-0.14782609  0.05217391  0.13043478]
 [ 0.13043478  0.13043478 -0.17391304]]


**Matrix multiplication**

In [5]:
import numpy as np
import sys
R1,R2 = map(int,input("Enter the number of rows for matrix A and B respectively:").split())
C1,C2 = map(int,input("Enter the number of column for matrix A and B respectively:").split())
if R2!=C1:
	sys.exit("wrong input value of R2 and C1")
print("Enter the elements for matrix A and B in a single line (separated by space): ")

entries1 = list(map(int, input().split()))
entries2 = list(map(int, input().split()))
A = np.array(entries1).reshape(R1, C1)
B = np.array(entries2).reshape(R2, C2)

print(np.dot(A,B))



Enter the number of rows for matrix A and B respectively:3 4
Enter the number of column for matrix A and B respectively:4 2
Enter the elements for matrix A and B in a single line (separated by space): 
2 4 6 8 1 6 3 9 8 2 5 4
3 2 7 8 5 4 6 1
[[112  68]
 [114  71]
 [ 87  56]]
