<a href="https://colab.research.google.com/github/Hussainaquib/Python-Programs/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NumPy***

creating one dimensional array

In [ ]:
import numpy as np
l =[1,2,3,4]
print("list in python:",l)
print(type(l))

a = np.array(l)
print("numpy array in python:",a)
print(type(a))

list in python: [1, 2, 3, 4]
<class 'list'>
numpy array in python: [1 2 3 4]
<class 'numpy.ndarray'>


creating multi-dimensional array

In [ ]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l3 = [9,10,11,12]
a = np.array([l1,l2,l3])
print("numpy multi dimensional array in python is:\n",a)

numpy multi dimensional array in python is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**checking dimensional ,shape and size of an array**

In [ ]:
# zero dimension
a = np.array(42)
print(a.ndim)
print(a.shape)
print(a.size)

0
()
1


In [ ]:
# one dimension
a = np.array([42])
# OR a = np.array((42,))
print(a.ndim)
print(a.shape)
print(a.size)

1
(1,)
1


In [ ]:
# one dimension
a = np.array([1,2,3,4,5])
# OR a = np.array((1,2,3,4,5))
print(a.ndim)
print(a.shape)
print(a.size)

1
(5,)
5


In [ ]:
# two dimension
a = np.array([[1,2,3],[4,5,6]])
# OR a = np.array(((1,2,3),(4,5,6)))
print(a.ndim)
print(a.shape)
print(a.size)

2
(2, 3)
6


In [ ]:
# three dimension
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
# OR a = np.array((((1,2,3),(4,5,6)),((1,2,3),(4,5,6))))
print(a.ndim)
print(a.shape)
print(a.size)

3
(2, 2, 3)
12


In [ ]:
# three dimension
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
# OR a = np.array((((1,2,3),(4,5,6)),((1,2,3),(4,5,6)),((1,2,3),(4,5,6))))
print(a.ndim)
print(a.shape)
print(a.size)

3
(3, 2, 3)
18


In [ ]:
# three dimension
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
''' OR a = np.array((((1,2,3),(4,5,6),(7,8,9)),
                    ((1,2,3),(4,5,6),(7,8,9)),
                    ((1,2,3),(4,5,6),(7,8,9))))'''
print(a.ndim)
print(a.shape)
print(a.size)

3
(3, 3, 3)
27


In [ ]:
# four dimension
a = np.array([1,2,3,4],ndmin=4)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)
4


In [ ]:
# four dimension
a = np.array([[[1,2,3],[4,5,6]]],ndmin=4)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[[1 2 3]
   [4 5 6]]]]
4
(1, 1, 2, 3)
6


In [ ]:
# four dimension
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],ndmin=4)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4
(1, 3, 2, 3)
18


In [ ]:
# five dimension
a = np.array([[[1,2,3],[4,5,6]]],ndmin=5)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[[[1 2 3]
    [4 5 6]]]]]
5
(1, 1, 1, 2, 3)
6


In [ ]:
# 100 dimension
a = np.array([1,2,3,4],ndmin=10)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)
4


**find the dimension,shape,size and data type of NumPy ndarray**

In [ ]:
import numpy as np
data1 = [6,7.5,8,0,1]
a = np.array(data1)
print(a)
print("\n")
print(a.ndim)
print("\n")
print(a.shape)
print("\n")
print(a.size)
print("\n")
print(a.dtype)
print("\n")

[6.  7.5 8.  0.  1. ]


1


(5,)


5


float64




In [ ]:
import numpy as np
data1 = [[1,2,3,4],[5,6,7,8]]
a = np.array(data1)
print(a)
print("\n")
print(a.ndim)
print("\n")
print(a.shape)
print("\n")
print(a.size)
print("\n")
print(a.dtype)
print("\n")

[[1 2 3 4]
 [5 6 7 8]]


2


(2, 4)


8


int64




**NumPy array creation using list ,tuple ,built in function and random function**

In [ ]:
# array() function

#creating 0-D array with value 42
a = np.array(42)
print(a)
print("\n")

#creating 1-D array with value 1,2,3,4,5:
b = np.array([1,2,3,4,5])
print(b)
print("\n")

#creating 2-D array with value 1,2,3 and 4,5,6:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print("\n")

#creating 3-D array with 2-D arrays,both containing two arrays values 1,2,3 and 4,5,6:
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d)
print("\n")

#creating an array with 5 dimension and verify that it has 5 dimensions:
e = np.array([1,2,3,4],ndmin = 5)
print(e)

42


[1 2 3 4 5]


[[1 2 3]
 [4 5 6]]


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


[[[[[1 2 3 4]]]]]


In [ ]:
# arange() function

print(np.arange(4,10))
print("\n")
print(np.arange(4,20,3))
print("\n")
print(np.arange(4).reshape(2,2))
print("\n")

[4 5 6 7 8 9]


[ 4  7 10 13 16 19]


[[0 1]
 [2 3]]




In [ ]:
# ones() function

b = np.ones(2)
print(b)
print("\n")
a = np.ones([2,2])
print(a)
print("\n")
c = np.ones([2,1,3])
print(c)

[1. 1.]


[[1. 1.]
 [1. 1.]]


[[[1. 1. 1.]]

 [[1. 1. 1.]]]


In [ ]:
# ones_like() function

array = np.arange(10)
print(array)
print("\n")
b = np.ones_like(array)
print(b)
print("\n")
array = np.arange(8)
c = np.ones_like(array)
print(c)

[0 1 2 3 4 5 6 7 8 9]


[1 1 1 1 1 1 1 1 1 1]


[1 1 1 1 1 1 1 1]


In [ ]:
# zeros() function

b = np.zeros(2)
print(b)
print("\n")
a = np.zeros([2,2])
print(a)
print("\n")
c = np.zeros([2,1,3])
print(c)

[0. 0.]


[[0. 0.]
 [0. 0.]]


[[[0. 0. 0.]]

 [[0. 0. 0.]]]


In [ ]:
# zeros_like() function
array = np.arange(10)
print(array)
print("\n")
b = np.zeros_like(array)
print(b)
print("\n")
array = np.arange(8)
c = np.zeros_like(array)
print(c)

[0 1 2 3 4 5 6 7 8 9]


[0 0 0 0 0 0 0 0 0 0]


[0 0 0 0 0 0 0 0]


In [ ]:
# full() function

a = np.full([2,2],67)
print(a)
print("\n")
c = np.full([3,3],10.1)
print(c)

[[67 67]
 [67 67]]


[[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


In [ ]:
# full_like() function

x = np.arange(10,dtype=int).reshape(2,5)
print(x)
print("\n")

print(np.full_like(x,10.0))
print("\n")

y = np.arange(10,dtype = float).reshape(2,5)
print(y)
print("\n")

print(np.full_like(y,0.01))

[[0 1 2 3 4]
 [5 6 7 8 9]]


[[10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


[[0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01]]


In [ ]:
# empty() function

b = np.empty(2,dtype = int)
print(b)
print("\n")

a = np.empty([2,2])
print(a)
print("\n")

c = np.empty([3,3])
print(c)

[0 0]


[[0. 0.]
 [0. 0.]]


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
# empty_like() function

x = np.arange(10).reshape(2,5)
print(x)
print("\n")

b = np.empty_like(x)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


[[4576918229304087675 4576918229304087675 4576918229304087675
  4576918229304087675 4576918229304087675]
 [4576918229304087675 4576918229304087675 4576918229304087675
  4576918229304087675 4576918229304087675]]


In [ ]:
# eye() function

#2x2 matrix with 1's on main diagonal
b = np.eye(2)
print(b)
print("\n")

# matrix with R = 4,C= 5 and 1 on diagonal below main diagonal
a = np.eye(4,5,k=+2)
print(a)

[[1. 0.]
 [0. 1.]]


[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# identity() function

#2x2 matrix with 1's on diagonal
b = np.identity(2,dtype = float)
print(b)
print("\n")

a = np.identity(4)
print(a)

[[1. 0.]
 [0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# rand() function

array = np.random.rand(5)
print(array)
print("\n")

array = np.random.rand(2,2,2)
print(array)

[0.21944951 0.36229969 0.63651992 0.54398769 0.25911053]


[[[0.91256648 0.15519384]
  [0.33802687 0.96523914]]

 [[0.8489191  0.74663101]
  [0.46480918 0.9730496 ]]]


**checking data type of array**

In [ ]:
# get the data type of an array object:
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
# get the data type of an array containing string:
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)
new_array = np.array(['michaeal','john','george'])
print(new_array.dtype)

<U6
<U8


In [ ]:
new_array = np.array([89.9,17.9,45.1])
print(new_array.dtype)

float64


**creating arrays with a defined data type**

In [ ]:
# creating ana array with data type 4 bytes integer:
arr = np.array([1,2,3,4],dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# a non integer string like 'a' can't be converted to integer (will raise an error):
arr = np.array(['a','2','3'],dtype='i4')

ValueError: ignored

**changing the data type of an existing array**

In [ ]:
x = np.array([12,24,36,48])
print(x)
print(f"data type of a : {x.dtype}")

x = x.astype('float64')
print(f"the data type of a after calling the astype function: {x.dtype}")
print(f"array a: {x}")


[12 24 36 48]
data type of a : int64
the data type of a after calling the astype function: float64
array a: [12. 24. 36. 48.]


In [ ]:
a = np.array([78.3,17.5,17.1,19.2])
a = a.astype('i')
print(a)

[78 17 17 19]


In [ ]:
#changing the type from float to integer by using character code 'i' as parameter value:
a = np.array([1.1,2.1,3.1])
b = a.astype('i')
print(b)
print(b.dtype)

[1 2 3]
int32


In [ ]:
#changing the type from float to integer by using character code 'int' as parameter value:
a = np.array([1.1,2.1,3.1])
b = a.astype(int)
print(b)
print(b.dtype)

[1 2 3]
int64


In [ ]:
# change data type from integer to boolean:
arr = np.array([1,0,3])
b = arr.astype(bool)
print(b)
print(b.dtype)


[ True False  True]
bool


In [ ]:
a = np.array([1,2,3,4,5])
print(a.dtype)
b = a.astype(np.float64)
print(b.dtype)

int64
float64


**Numpy array with mixed data types**

In [ ]:
res  = np.array([("john",15,14),("george",13,21)],dtype='|S4,i4,i4')
print(res)

[(b'john', 15, 14) (b'geor', 13, 21)]


In [ ]:
a = np.array([('pos',(78,15,28)),('sop',(10,26,87))],dtype = '3a,3i')
print(a)

[(b'pos', [78, 15, 28]) (b'sop', [10, 26, 87])]


In [ ]:
a = np.array([89,45,21,98],dtype='S')
b = np.array([91,22,87,65],dtype='i4')
print(a.dtype)
print(b.dtype)

|S2
int32


In [ ]:
a = np.dtype('uint8')
print(a)
b = np.array([87,45,12,98],dtype='uint8')
print(b.dtype)

uint8
uint8


**Arithmetic operations with NumPy Array**

add operation

In [ ]:
import numpy as np
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = np.add(arr1,arr2)
print(newarr)

[22 24 26 28 30 32]


subtract operation

In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = np.subtract(arr1,arr2)
print(newarr)

[0 0 0 0 0 0]


multiplication operation

In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = np.multiply(arr1,arr2)
print(newarr)

[121 144 169 196 225 256]


division operation

In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = np.divide(arr1,arr2)
print(newarr)

[1. 1. 1. 1. 1. 1.]


remainder operation

In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = np.mod(arr1,arr2)
print(newarr)

[0 0 0 0 0 0]


In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = np.remainder(arr1,arr2)
print(newarr)

[0 0 0 0 0 0]


using +,-,*,/ operator

In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = arr1+arr2
print(newarr)

[22 24 26 28 30 32]


In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = arr1-arr2
print(newarr)

[0 0 0 0 0 0]


In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = arr1*arr2
print(newarr)

[121 144 169 196 225 256]


In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = arr1/arr2
print(newarr)

[1. 1. 1. 1. 1. 1.]


In [ ]:
arr1=np.array([11,12,13,14,15,16])
arr2=np.array([11,12,13,14,15,16])
newarr = arr1%arr2
print(newarr)

[0 0 0 0 0 0]


**indexing in Numpy**

indexing in one dimensional array

In [ ]:
import numpy as np
arr =np.array([4,7,2])
print(arr)
print("\n")
print(arr[1])

[4 7 2]


7


In [ ]:
array1 = np.arange(0,10)
print(array1)
print("\n")
print(array1[2])

[0 1 2 3 4 5 6 7 8 9]


2


indexing in two dimensional array

In [ ]:
arr = np.array([[2,3,4],[1,2,5],[3,4,3]])
print(arr)
print(arr[1,2])

[[2 3 4]
 [1 2 5]
 [3 4 3]]
5


In [ ]:
array1 = np.arange(12).reshape(4,3)
print(array1)
print(array1[3][1])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
10


indexing a three dimensional array

In [ ]:
array1 = np.arange(18).reshape(3,2,3)
print(array1)
print(array1[2][0][1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
13


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print("\n")
print(arr[0])
print("\n")
print(arr[1,0])
print("\n")
print(arr[1][0])
print("\n")
print(arr[1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[1 2 3]
 [4 5 6]]


[7 8 9]


[7 8 9]


[[ 7  8  9]
 [10 11 12]]


Boolean indexing

In [ ]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)
print("\n")
print(x[x>5])
print(x[x<5])
print(x[x==5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[ 6  7  8  9 10 11]
[0 1 2 3 4]
[5]


In [ ]:
# using >= or <= operator
x = np.array([[42,56,89,65],[99,88,42,12],[55,42,17,18]])
print(x[x<=42])
print(x[x>=42])

[42 42 12 42 17 18]
[42 56 89 65 99 88 42 55 42]


In [ ]:
# using % or power (**) operator

x  = np.array([10,40,80,50,100])
print(x[x%40==0]**2)

[1600 6400]


In [ ]:
# using two condition with logical or '|'

x = np.array([[5,5],[4,5],[16,4]])
print(x[(x%2==0) | (x%3==0)])

[ 4 16  4]


Question:- Extract from the array np.array([3,4,6,10,24,89,45,43,46,99,100]) with Boolean indexing all the numbers. which are not divisible by 3
,which are divisible by 5
,which are divisible by 3 and 5
,which are divisible by 3 and set them to 42

In [ ]:
a = np.array([3,4,6,10,24,89,45,43,46,99,100])

div3 = a[a%3!=0]
print(div3)
print("\n")
div5 = a[a%5==0]
print(div5)
print("\n")
print(a[(a%3==0) & (a%5==0)])
print("\n")
a[a%3==0] = 42
print(a)

[  4  10  89  43  46 100]


[ 10  45 100]


[45]


[ 42   4  42  10  42  89  42  43  46  42 100]


one dimensional negative indexing

In [ ]:
arr = np.array([4,7,2])
print(arr)
print("\n")
print(arr[-3])

[4 7 2]


4


two dimensional negative indexing

In [ ]:
arr = np.array([[2,3,4],[1,2,5],[3,4,3]])
print(arr)
print("\n")
print(arr[-1,-2])

[[2 3 4]
 [1 2 5]
 [3 4 3]]


4


three dimensional negative indexing

In [ ]:
arr = np.array([[[2,1],[4,5],[6,2]],[[3,4],[7,6],[10,2]]])
print(arr)
print("\n")
print(arr[-1,-2,-1])

[[[ 2  1]
  [ 4  5]
  [ 6  2]]

 [[ 3  4]
  [ 7  6]
  [10  2]]]


6


combining positive and negative indexes

In [ ]:
arr = np.array([[2,3,4],[1,2,5],[3,4,3]])
print(arr)
print("\n")
print(arr[-2,2])

[[2 3 4]
 [1 2 5]
 [3 4 3]]


5


calculate the prime number between 0 and 100 by using a boolean array

In [ ]:
is_prime = np.ones((100,),dtype=bool)
is_prime[:2] = 0
nmax = int(np.sqrt(len(is_prime)))
for i in range(2, nmax):
  is_prime[2*i::i] = False
print(np.nonzero(is_prime)) 

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97]),)


**Slicing in NumPy**

slicing in one dimensional array

In [ ]:
import numpy as np
arr = np.arange(9)
print(arr)
print(arr[3:6])
print(arr[:])
print(arr[4:])
print(arr[:7])

[0 1 2 3 4 5 6 7 8]
[3 4 5]
[0 1 2 3 4 5 6 7 8]
[4 5 6 7 8]
[0 1 2 3 4 5 6]


In [ ]:
# to modify the item in array
arr = np.array([1,2,3,4,5])
print(arr)
a = arr[1:4]
print(a)
a[1] = 10
print(a)
print(arr)

[1 2 3 4 5]
[2 3 4]
[ 2 10  4]
[ 1  2 10  4  5]


In [ ]:
# for jump the elements
arr = [0,1,2,3,4,5,6,7,8,9,10]
print(arr[2:10:2])

[2, 4, 6, 8]


slicing a two dimensional array

In [ ]:
arr = np.arange(16).reshape(4,4)
print(arr)
print("\n")
print(arr[0:2,1:3])

In [ ]:
arr = np.arange(20).reshape(4,5)
print(arr)
print("\n")
print(arr[1:,2:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 7  8]
 [12 13]
 [17 18]]


slicing in three dimensional array

In [ ]:
arr = np.array([[[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]]])
print(arr)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
arr = np.array([[[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]]])
print(arr[:2,1:,:2])

[[[13 14]
  [16 17]]

 [[13 14]
  [16 17]]]


In [ ]:
arr = np.array([[[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]]])
print(arr[:,:,:])

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
arr = np.array([[[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]]])
print(arr[1:,:,:])
print("\n")
print(arr[1:,:])
print("\n")
print(arr[1:])

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
arr = np.array([[[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]],
                [[10,11,12],[13,14,15],[16,17,18]]])
print(arr[1:3,:])
print("\n")
print(arr[1:3])

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


slicing using negative indexing

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)
print(arr[-6])

[10 20 30 40 50 60 70 80 90]
40


In [ ]:
# using negative values for both the indices
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)
print(arr[-3:-1])

[10 20 30 40 50 60 70 80 90]
[70 80]


In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)
print(arr[-1:-3])

[10 20 30 40 50 60 70 80 90]
[]


**Transposing NumPy Arrays**

NumPy Transpose 1-D array

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)
print("\n")
arr2 = arr1.transpose()
print(arr2)
print("\n")
arr3 = arr1.T
print(arr3)

#print the shape of the two arrays
print("Original array shape:",arr1.shape)
print("shape after transpose:",arr2.shape)
print("shape after transpose:",arr3.shape)

[1 2 3 4]


[1 2 3 4]


[1 2 3 4]
Original array shape: (4,)
shape after transpose: (4,)
shape after transpose: (4,)


In [ ]:
# array transpose by arange function
arr1 = np.arange(3)
print(arr1)
print("\n")
print(arr1.transpose())
print("\n")
# or 
# print(arr1.T)
#or
# print(np.transpose(arr1))

[0 1 2]


[0 1 2]




NumPy Transpose 2-D array

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print("\n")
arr2 = arr1.transpose()
print(arr2)
print("\n")
#or
# arr1 = arr2.T
# print(arr2)

#print the shape of two arrays
print("Original array shape:",arr1.shape)
print("Original array shape:",arr2.shape)

[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]


Original array shape: (2, 3)
Original array shape: (3, 2)


In [ ]:
# array transposing using arange function
arr1 = np.arange(15).reshape((3,5))
print(arr1)
print("\n")
arr2 = arr1.transpose()
print(arr2)
print("\n")
#or 
 #   arr2 = arr1.T()
  #  print(arr2) 


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]




NumPy Transposing in 3-D array

In [ ]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)
print("\n")
arr2 = arr1.transpose()
print(arr2)
print("\n")
print("Original array shape:",arr1.shape)
print("Shape after transpose:",arr2.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


Original array shape: (2, 2, 4)
Shape after transpose: (4, 2, 2)


NumPy transposing in 4-D array

In [ ]:
arr1 = np.full((2,3,4,5),8)
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print("\n")
arr2 = arr1.transpose()
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[[[8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]]

  [[8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]]

  [[8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]]]


 [[[8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]]

  [[8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]]

  [[8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]
   [8 8 8 8 8]]]]
4
(2, 3, 4, 5)


[[[[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]]


 [[[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]]


 [[[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]]


 [[[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]]


 [[[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]

  [[8 8]
   [8 8]
   [8 8]]]]
4
(5, 4, 3, 2)


**Swapping NumPy Arrays**

using index position

In [ ]:
import numpy as np
my_array= np.arange(12).reshape(4,3)
print("original array :")
print(my_array)

#swappimg the column with index of original array
my_array[:,[0,2]]=my_array[:,[2,0]]
print("After swapping arrays the last column and first column:")
print(my_array)

original array :
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping arrays the last column and first column:
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


using swapaxes

In [ ]:
a = np.array([[2,3,4]])
print(a)
print("\n")
print(np.swapaxes(a,0,1)) # same as transpose

[[2 3 4]]


[[2]
 [3]
 [4]]


In [ ]:
x = np.array([[1,2,3],[20,30,40],[100,200,300]])
print(x)
print("\n")
y=np.swapaxes(x,0,1)
print(y)

[[  1   2   3]
 [ 20  30  40]
 [100 200 300]]


[[  1  20 100]
 [  2  30 200]
 [  3  40 300]]


In [ ]:
x = np.array([[[1,2,3],[20,30,40]],[[5,55,555],[9,9,9]]])
print(x)
print("\n")
z = np.swapaxes(x,0,2)
print(z)

[[[  1   2   3]
  [ 20  30  40]]

 [[  5  55 555]
  [  9   9   9]]]


[[[  1   5]
  [ 20   9]]

 [[  2  55]
  [ 30   9]]

 [[  3 555]
  [ 40   9]]]


In [ ]:
# create a three dimensional array
import numpy as np
a = np.arange(16).reshape(2,2,2,2)
print(a)
print("\n")
print("\n")
# now swap numbers between axis 0 (along depth) and axis 2 (along width)
print(np.swapaxes(a,0,0))
print("\n")
print("\n")
print(np.swapaxes(a,0,1))
print("\n")
print("\n")
print(np.swapaxes(a,0,2))
print("\n")
print("\n")
print(np.swapaxes(a,0,3))
print("\n")
print("\n")

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]




[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]




[[[[ 0  1]
   [ 2  3]]

  [[ 8  9]
   [10 11]]]


 [[[ 4  5]
   [ 6  7]]

  [[12 13]
   [14 15]]]]




[[[[ 0  1]
   [ 8  9]]

  [[ 4  5]
   [12 13]]]


 [[[ 2  3]
   [10 11]]

  [[ 6  7]
   [14 15]]]]




[[[[ 0  8]
   [ 2 10]]

  [[ 4 12]
   [ 6 14]]]


 [[[ 1  9]
   [ 3 11]]

  [[ 5 13]
   [ 7 15]]]]






In [ ]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print("\n")
print(np.swapaxes(a,0,1))
print("\n")
print(np.swapaxes(a,1,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]


**Universal Function
  1- Arithematic function
  2- Mathematical function
  3- Statistical function
  4- Set function
  5- Fast element wise Array function**

**1-Mathematical function**

floor() function

In [ ]:
import numpy as np
arr = np.floor([-3.1666,3.6667])
print(arr)

[-4.  3.]


ceil() function

In [ ]:
import numpy as np
arr = np.ceil([-3.1666,3.6667])
print(arr)

[-3.  4.]


log() function

In [ ]:
import numpy as np
arr = np.arange(1,10)
print(np.log(arr ))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


cumsum() function

In [ ]:
import numpy as np
arr = np.array([1,2,3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


cumprod() function

In [ ]:
import numpy as np
arr = np.array([5,6,7,8])
newarr = np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


lcm() function

In [ ]:
import numpy as np
num1 = 4
num2 = 6
x = np.lcm(num1,num2)
print(x)

12


gcd() function

In [ ]:
import numpy as np
num1 = 6
num2 = 9
x = np.gcd(num1,num2)
print(x)

3


reciprocal() function

In [ ]:
import numpy as np
print(np.reciprocal([1,2.,3.33]))

[1.        0.5       0.3003003]


**2-Statistical function**

The statistical function is amin , amax , mean , std , var , average , percentile(a,p,axis)

In [ ]:
import numpy as np
weight = np.array([50.7,52.5,50,58,55.63,73.25,49.5,45])

# minimum and maximum
print('minimum and maximum weight of students:')
print(np.amin(weight),np.amax(weight))

# percentile
print('weight below which 70% students fall:')
print(np.percentile(weight,70))

# mean
print('mean weight of the students:')
print(np.mean(weight))

# median
print('median weight of the students:')
print(np.median(weight))

# standard deviation
print('standart deviation weight of the students:')
print(np.std(weight))

# variance
print('variance weight of the students:')
print(np.var(weight))

# average
print('average weight of the students:')
print(np.average(weight))

minimum and maximum weight of students:
45.0 73.25
weight below which 70% students fall:
55.317
mean weight of the students:
54.3225
median weight of the students:
51.6
standart deviation weight of the students:
8.052773978574091
variance weight of the students:
64.84716875
average weight of the students:
54.3225


**3-Set function**

unique() function

In [ ]:
arr = np.array([1,1,1,2,3,4,5,5,6,7])
x=np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


union1d() function

In [ ]:
arr1 = np.array([[1,2,3,4],[11,22,23,44]])
arr2 = np.array([[11,22,23,4],[1,2,3,44]])
print(arr1)
newarr = np.union1d(arr1,arr2)
print(newarr)

[[ 1  2  3  4]
 [11 22 23 44]]
[ 1  2  3  4 11 22 23 44]


intersect1d() function

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])
print(arr1)
newarr = np.intersect1d(arr1,arr2,assume_unique=True)
print(newarr)

[1 2 3 4]
[3 4]


setdiff1d() function

In [ ]:
arr1 = np.array([[1,2,3,4],[11,22,23,44]])
arr2 = np.array([[11,22,23,4],[1,2,3,44]])
print(arr1)
newarr = np.setdiff1d(arr1,arr2,assume_unique=True)
print(newarr)

[[ 1  2  3  4]
 [11 22 23 44]]
[]


setxor1d() function

In [ ]:
set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])
print(arr1)
newarr = np.setxor1d(set1,set2,assume_unique=True)
print(newarr)

[[ 1  2  3  4]
 [11 22 23 44]]
[1 2 5 6]


**5-Fast element-wise Array Function**

Bitwise function that is and , or , xor , invert , left shift , right shift 

In [ ]:
import numpy as np
even = np.array([0,2,4,6,8,16,32])
odd = np.array([1,3,5,7,9,17,33])

# bitwise_and
print('bitwise_and of two arrays:')
print(np.bitwise_and(even,odd))

# bitwise_or
print('bitwise_or of two arrays:')
print(np.bitwise_or(even,odd))

# bitwise_xor
print('bitwise_xor of two arrays:')
print(np.bitwise_xor(even,odd))

# invert or not
print('inversion pf even no. array:')
print(np.invert(even))

a = np.array([1])

# left_shift
print('left_shift of array:')
print(np.left_shift(a,3))

# right shift
print('right_shift of array:')
print(np.right_shift(a,0))

bitwise_and of two arrays:
[ 0  2  4  6  8 16 32]
bitwise_or of two arrays:
[ 1  3  5  7  9 17 33]
bitwise_xor of two arrays:
[1 1 1 1 1 1 1]
inversion pf even no. array:
[ -1  -3  -5  -7  -9 -17 -33]
left_shift of array:
[8]
right_shift of array:
[1]


Comparison Function that is '>' , '>=' , '<' , '<=' , '!=' , '=='

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
b= np.array([12,32,56,4,3,8,23,9,18,1])

print(a>b)
print("\n")
print(a>=b)
print("\n")
print(a<b)
print("\n")
print(a<=b)
print("\n")
print(a!=b)
print("\n")
print(a==b)

[False False False False  True False False False False  True]


[False False False  True  True False False False False  True]


[ True  True  True False False  True  True  True  True False]


[ True  True  True  True False  True  True  True  True False]


[ True  True  True False  True  True  True  True  True  True]


[False False False  True False False False False False False]


Logical Function that is logical_and , logical_or , logical_xor , logical_not

In [ ]:
import numpy as np
# logical_and
x = np.arange(15)
print(x)
print("\n")

np.logical_and(x>1,x<4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]




array([False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
import numpy as np
# logical_or
x = np.arange(15)
print(x)
print("\n")

np.logical_or(x>1,x<4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]




array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
import numpy as np
# logical_xor
x = np.arange(15)
print(x)
print("\n")

np.logical_xor(x>1,x<4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]




array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
import numpy as np
# logical_not
x = np.arange(15)
print(x)
print("\n")

np.logical_not(x>1,x<4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]




array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

**NumPy Sorting**

Sorting 1-D numpy array (Ascending Order)

In [ ]:
import numpy as np
a = np.array([32,4,8,12,20])
print('Original array is',a)
print('Sorted array is',np.sort(a))

Original array is [32  4  8 12 20]
Sorted array is [ 4  8 12 20 32]


In [ ]:
a = np.array(['b','a','h','e','k'])
sorted_array = (np.sort(a))
print(sorted_array)

['a' 'b' 'e' 'h' 'k']


In [ ]:
a = np.array(['John','Micheal','George'])
sorted_array = (np.sort(a))
print(sorted_array)

['George' 'John' 'Micheal']


sort 1-D numpy array (Descending order)

In [ ]:
array = np.array([5,8,6,12])
array[::-1].sort()
print(array)

[12  8  6  5]


Sorting 2-D NumPy Array

In [ ]:
import numpy as np
a = np.array([[32,4,8,12,30],[35,5,15,10,20]])
print("Sorted array when axis is None\n",np.sort(a,axis=None))
print("\n")
print("Sorted array when axis is 0\n",np.sort(a,axis=0))
print("\n")
print("Sorted array when axis is 1\n",np.sort(a,axis=1))

Sorted array when axis is None
 [ 4  5  8 10 12 15 20 30 32 35]


Sorted array when axis is 0
 [[32  4  8 10 20]
 [35  5 15 12 30]]


Sorted array when axis is 1
 [[ 4  8 12 30 32]
 [ 5 10 15 20 35]]


Sorting NumPy 3-D Array

In [ ]:
import numpy as np

arr = np.array([[[12,15,7],[13,5,11]],[[8,6,10],[45,54,70]]])
print("array:\n",arr)

arr2 = np.sort(arr)
print("sorted array:\n",arr2)

arr2 = np.sort(arr,axis=-1)
print("Sorted array along axis=-1:\n",arr2)           

array:
 [[[12 15  7]
  [13  5 11]]

 [[ 8  6 10]
  [45 54 70]]]
sorted array:
 [[[ 7 12 15]
  [ 5 11 13]]

 [[ 6  8 10]
  [45 54 70]]]
Sorted array along axis=-1:
 [[[ 7 12 15]
  [ 5 11 13]]

 [[ 6  8 10]
  [45 54 70]]]


Multidimensional numpy array sorting along specific axis

In [ ]:
# along axis None 

arr = np.array([[12,15,7],[13,5,11],[8,6,10],[45,54,70]])
arr2 = np.sort(arr,axis=None)
print("Sorted array:\n",arr2)

Sorted array:
 [ 5  6  7  8 10 11 12 13 15 45 54 70]


In [ ]:
# along axis=0

arr2 = np.sort(arr,axis=0)
print("Sorted array:\n",arr2)

Sorted array:
 [[ 8  5  7]
 [12  6 10]
 [13 15 11]
 [45 54 70]]


In [ ]:
# along axis = 1

arr = np.array([[12,15,7],[13,5,11],[8,6,10],[45,54,70]])
arr2 = np.sort(arr,axis = 1)
print("Sorted array:\n",arr2)

Sorted array:
 [[ 7 12 15]
 [ 5 11 13]
 [ 6  8 10]
 [45 54 70]]


Apply Sorting Algorithms

In [ ]:
arr = np.array([2,1,4,3,5])

# selection sort
b = np.sort(arr,kind='selectionsort')
print(b)
print("\n")

# quick sort
e = np.sort(arr,kind='quicksort')
print(e)
print("\n")

# heap sort
f = np.sort(arr,kind='heapsort')
print(f)
print("\n")

# merge sort
g = np.sort(arr,kind='mergesort')
print(g)
print("\n")

[1 2 3 4 5]


[1 2 3 4 5]


[1 2 3 4 5]


[1 2 3 4 5]


